# Generated by Django 3.2.7 on 2021-11-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20211117_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedadanonima',
            name='encrypted_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
