# Generated by Django 3.2.7 on 2021-11-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_sociedadanonima_encrypted_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedadanonima',
            name='id_caso',
            field=models.IntegerField(null=True),
        ),
    ]
