# Generated by Django 3.2.7 on 2021-11-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_sociedadanonima_id_caso'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedadanonima',
            name='file_id_drive',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
