# Generated by Django 3.2.7 on 2021-11-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_sociedadanonima_file_id_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedadanonima',
            name='numero_expediente',
            field=models.CharField(max_length=30, null=True, verbose_name='Numero de expediente'),
        ),
    ]
