# Generated by Django 3.2.7 on 2021-12-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_sociedadanonima_carpeta_fisica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociedadanonima',
            name='file_id_drive',
        ),
    ]
